remote_theme: pages-themes/cayman@v0.2.0
title: ðŸ¦¥ SlothAPI
description:  My Python Web Framework Study Project
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
